### ISSUE TITLE
Trouble using Nilaway

### ISSUE THREAD

**Issue by dev-ns8** [uber-go/nilaway#145]
I'm looking for some guidance on using nilaway.  I am attempting to build and run the tool from source and analyze a project of mine. 

Let's say my project's directory is: `/Users/me/projects/MyProject`
Let's say `nilaway` source is located: `/Users/me/projects/nilaway`

So from nilaways directory I'm running: 
`go run cmd/nilaway/main.go ../MyProject/...` 

I have tried this for numerous of my projects, and I continue to get the same error from nilaway: 

`-: pattern ../../projects/go-vpn/...: directory prefix ../../projects/go-vpn does not contain main module or its selected dependencies`

Wondering if someone could point me in the right direction on how to run nilaway on some of my personal code? 

Thanks.

**Comment by dev-ns8** [comment]
> Hi @dev-ns8 , For using NilAway, you only need to navigate to your project's root directory, then run the following command to install NilAway: `go install go.uber.org/nilaway/cmd/nilaway@latest`
> 
> Then run the following command to run NilAway on you projects: `nilaway ./...`


I want to run nilaway from the source so I can attach a debugger to the process. Is there no way to run nilaway without installing it?

**Comment by yuxincs** [comment]
You can run nilaway from source by going to the target repository you want to analyze and then `go run ../nilaway/cmd/nilaway/main.go ./...`

The Go module pattern we support is the same as the `go list` command, you can also run `go help packages` to see how the patterns can be used 😃 

Closing since I think it's resolved, but feel free to reopen if for some reason it doesn't!
