### ISSUE TITLE
Nilaway execute detection recursively in all of the dependencies

### ISSUE THREAD

**Issue by sejin-P** [uber-go/nilaway#16]
I want an option that Nilaway only detects in a certain repo.

**Comment by sejin-P** [comment]
Thank you for your comment, @yuxincs ! I read that wiki, and is `include-pkgs` meaning that analyze only 'included pkgs' in values? In my opinion, most people want that nilaway analyzes all of the packages in a repo, except for the dependencies.

**Comment by yuxincs** [comment]
`include-pkgs` is meant to be a list of _prefixes_ that NilAway analyzes (e.g., `-include-pkgs=go.uber.org` will make NilAway only analyze any packages with the prefix `go.uber.org` (e.g., `go.uber.org/nilaway/accumulation`).

Note that there's a different between _analyzed_ and _reported_. Here the `include-pkgs` is intended to ignore analysis mostly for better performance (plus the errors reported in them can't be easily fixed by the devs anyways), but errors could still be reported on them:

> ⚠️ Please note that even if a package is excluded from analysis, errors might still be reported on them if the nilness flows happens within the analyzed package, but it includes using a struct from the excluded package. For example, if the analyzed package constructs a struct from the excluded package, assigns a nil to a field, and then immediately dereferences the field. In this case, NilAway will report an error for this flow, but the location will be on the field (that resides in the excluded package). To only report errors on the desired packages, please use the error suppression mechanisms specified in the driver ([golangci-lint](https://golangci-lint.run/usage/false-positives/), [nogo](https://github.com/bazelbuild/rules_go/blob/master/go/nogo.rst)).

But if what you wanted is to suppress errors on the other packages, you should use your driver to do that. For the standalone driver, we have added two more flags for error suppression:

```
-include-errors-in-files string
    	A comma-separated list of file prefixes to report errors, default is current working directory.
-exclude-errors-in-files string
    	A comma-separated list of file prefixes to exclude from error reporting. This takes precedence over include-errors-in-files.
```

**Comment by lazaroclapp** [comment]
>  In my opinion, most people want that nilaway analyzes all of the packages in a repo, except for the dependencies

This is achievable by giving it your org's package prefix (e.g. `go.uber.org` for us) as `-include-pkgs` and the root of your repo as `-include-errors-in-files` (which should be the default if you run nilaway from that dir). 

Also note that there is a case for asking it to analyze dependencies too, depending on how big a performance hit you get from that, as that way it will be able to catch cases where you are getting `nil` values out of third-party libraries and then failing to check before dereferencing them.

**Comment by sejin-P** [comment]
@yuxincs @lazaroclapp Thank you for your detailed explanation.
