### ISSUE TITLE
False positive Observed nil flow from source to dereference point with return

### ISSUE THREAD

**Issue by mhmxs** [uber-go/nilaway#163]
Here is my example:

```golang
type Test struct {
	nilField *int
}

func Main() {
	t := &Test{}

	if false {
		A(t)

		return
	}

	
	B(t)
}

func A(t *Test) {
	t.nilField = nil
}

func B(t *Test) {
	println(*t.nilField)
}
```

If I ran nilaway, i got the following error:

```
test.go:26:11: error: Potential nil panic detected. Observed nil flow from source to dereference point: 
        -> controller/test.go:22:15: literal `nil` assigned into field `nilField`
        -> controller/test.go:26:11: field `nilField` dereferenced
```

The `println(*t.nilField)` fails at B because of `t.nilField = nil` at A, but after calling A, we have a return statement, so it doesn't affects B at all. Maybe it makes sense to take a look :pray: .

**Comment by yuxincs** [comment]
Handling struct fields is tricky, and we actually have an experiment-experimental feature (NilAway itself should be considered experimental) named struct initialization support for cases like this, and it is currently hidden behind a magic file comment `//<nilaway struct enable>`.

If you add that comment to the file header, NilAway will enable this feature for that particular file, and I have confirmed that NilAway will correctly throw the error indicating that the `nilField` is never assigned in the execution path to `B()` (and the error will go away if you assign the field to a nonnil value.

We are not enabling this feature by default because it brings non-negligible performance cost and false positives, and we are currently trying our best to optimize this feature further before fully merging it and enabling it by default. 

In the meantime, we will try to add a flag to make it more accessible to the users 😃

**Comment by mhmxs** [comment]
> <nilaway struct enable>

Thanks @yuxincs for your quick answer. I tried to change my code, but didn't help.

```golang
// <nilaway struct enable>
package test
```

Give me the same error:
```
ok
/home/rkovacs/src/github.com/uber-go/nilaway/test.go:25:11: error: Potential nil panic detected. Observed nil flow from source to dereference point: 
        -> nilaway/test.go:17:4: uninitialized field `nilField` of argument 0 to `B()`
        -> nilaway/test.go:25:11: field `nilField` dereferenced
```
`ok` int the first line verifies the comment has been found:

```golang
func DocContainsStructInitCheck(group *ast.CommentGroup) config.StructInitCheckType {
	if docContainsString(config.NilAwayStructInitCheckString)(group) {
		println("ok")
		return config.DepthOneFieldCheck
	}
	return config.NoCheck
}
```

:pray:

**Comment by yuxincs** [comment]
@mhmxs This is expected, right? since you did not initialize the pointer `t := &Test{}`, therefore the `nilField` is a by default `nil`. Then when you call `B`, it would eventually result in a nil panic.

If right before the call to `B`, you assign a nonnil value to the field, the error should go away.

BTW PR #178 should make it easier to turn on/off this experimental feature 😃

**Comment by mhmxs** [comment]
> This is expected, right?

Yes @yuxincs , i found the bug in the example which i did based on my original code. My bad, so after the fix, `<nilaway struct enable>` works as expected. :pray:
