### ISSUE TITLE
False positive for self referencing type in for loop 

### ISSUE THREAD

**Issue by ferhatelmas** [uber-go/nilaway#206]
```go
type Node struct {
	children map[rune]*Node
}

func Insert(root *Node, key string) {
	if root == nil {
		return
	}
	current := root
	for _, v := range key {
		if current.children == nil {
			current.children = make(map[rune]*Node)
		}
		if current.children[v] == nil {
			current.children[v] = &Node{
				children: make(map[rune]*Node),
			}
		}
		
		// deep read from field `children` lacking guarding; accessed field `children` via the assignment
		current = current.children[v] 
	}
}
```

**Comment by yuxincs** [comment]
Hi! 

Here I believe the problem is that NilAway is reporting the fact that you're reading from the map without guards (i.e., `current, ok := current.children[v]`), making `current` nilable.

However, here you have already checked `if current.children[v] == nil ` before the access, and NilAway currently doesn't track that. We are aware of this issue and are actually already brewing a PR to support that! Stay tuned for updates :)
